name: build-develop
on:
  push: # develop Branch 에서 push 이벤트가 일어났을 때만 수행
    branches:
      - develop

jobs:
  build-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master Branch
      - uses: actions/checkout@v2
        with:
          ref: develop

      - name: Run yarn install
        run: yarn

      - name: Run yarn build
        run: yarn build

      - name: Push new files back to master.
        uses: mikeal/publish-to-github-action@1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
