name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: build # The branch the action should deploy to.
          BUILD_SCRIPT: yarn && yarn build # The build script the action should run prior to deploying.
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
