name: Push
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create local changes
        run: |
          yarn
          yarn build
      - name: Commit files
        run: |
          git config --local user.email "devjang2016@gmail.com"
          git config --local user.name "devJang"
          git commit -m "Add changes" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
