# name: publish

# on:
#   push:
#     branches:
#       - master

# jobs:
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: checkout
#         uses: actions/checkout@master
#         with:
#           ref: master
#       - run: yarn
#       - run: yarn build
#       - name: Git Commit and Push
#         uses: github-actions-x/commit@v2.2
#         with:
#           github-token: ${{ secrets.GITHUB_TOKEN }}
#           push-branch: 'build'
#           commit-message: 'build'
#           force-add: 'true'
