name: 'Compile Typescript Workflow'

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Test Github action
    runs-on: ubuntu-latest
    steps:
      - run: yarn install
      - run: yarn build
