name: 'Compile Typescript Workflow'

on:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    name: Test Github action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: yarn install
      - run: yarn build
      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: chmod +x ./deploy-tag.sh
