name: 'Compile Typescript Workflow'

on:
  push:
    branches:
      - master
      - 'releases/*'
  tags:
    - v1

jobs:
  build:
    name: Test Github action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Build
      - uses: actions/setup-node@v1
        - run: yarn install
        - run: yarn build

