name: 'Compile Typescript Workflow'

on:
  push:
    branches:
      - master
      - 'releases/*'

jobs:
  build:
    name: Test Github action
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - run: yarn install
      - run: yarn build
      - name: Git Commit and Push
        uses: github-actions-x/commit@v2.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          push-branch: build
          commit-message: 'Update Build'
          rebase: 'true'
